// Descriptive errors mapping
export const DESCRIPTIVE_ERRORS = [
  { id: "display_error", label: "Błąd wyświetlacza" },
  { id: "main_operation", label: "Główne działanie" },
  { id: "mechanical_damage", label: "Uszkodzenie mechaniczne" },
  { id: "vacuum_error", label: "Błąd próżni" },
  { id: "deformed_plastic", label: "Zdeformowany plastik" },
  { id: "wet_load", label: "Wilgotny wsad" },
  { id: "door_housing_mismatch", label: "Niedopasowana obudowa drzwi" },
  { id: "door_opening_problem", label: "Problem z otwieraniem drzwi" },
  { id: "water_leak", label: "Wyciek / przeciek wody" },
]

// Mapowanie krajów do prefiksów telefonicznych
const COUNTRY_PHONE_PREFIXES_BASE: Record<string, string> = {
  poland: "+48",
  germany: "+49",
  czechia: "+420",
  slovakia: "+421",
}

export const COUNTRY_PHONE_PREFIXES: Record<string, string> = {
  ...COUNTRY_PHONE_PREFIXES_BASE, // Keep existing entries
  afghanistan: "+93",
  albania: "+355",
  algeria: "+213",
  andorra: "+376",
  angola: "+244",
  argentina: "+54",
  armenia: "+374",
  australia: "+61",
  austria: "+43",
  azerbaijan: "+994",
  bahamas: "+1-242",
  bahrain: "+973",
  bangladesh: "+880",
  barbados: "+1-246",
  belarus: "+375",
  belgium: "+32",
  belize: "+501",
  benin: "+229",
  bermuda: "+1-441",
  bhutan: "+975",
  bolivia: "+591",
  "bosnia-herzegovina": "+387",
  brazil: "+55",
  bulgaria: "+359",
  cambodia: "+855",
  cameroon: "+237",
  canada: "+1",
  chile: "+56",
  china: "+86",
  colombia: "+57",
  "costa-rica": "+506",
  croatia: "+385",
  cyprus: "+357",
  denmark: "+45",
  ecuador: "+593",
  egypt: "+20",
  estonia: "+372",
  ethiopia: "+251",
  finland: "+358",
  france: "+33",
  georgia: "+995",
  ghana: "+233",
  greece: "+30",
  guatemala: "+502",
  honduras: "+504",
  "hong-kong": "+852",
  hungary: "+36",
  iceland: "+354",
  india: "+91",
  indonesia: "+62",
  iran: "+98",
  iraq: "+964",
  ireland: "+353",
  israel: "+972",
  italy: "+39",
  japan: "+81",
  jordan: "+962",
  kazakhstan: "+7",
  kenya: "+254",
  "south-korea": "+82",
  kuwait: "+965",
  latvia: "+371",
  lebanon: "+961",
  libya: "+218",
  lithuania: "+370",
  luxembourg: "+352",
  malaysia: "+60",
  malta: "+356",
  mexico: "+52",
  moldova: "+373",
  monaco: "+377",
  mongolia: "+976",
  montenegro: "+382",
  morocco: "+212",
  netherlands: "+31",
  "new-zealand": "+64",
  nigeria: "+234",
  norway: "+47",
  pakistan: "+92",
  peru: "+51",
  philippines: "+63",
  portugal: "+351",
  qatar: "+974",
  romania: "+40",
  russia: "+7",
  "saudi-arabia": "+966",
  serbia: "+381",
  singapore: "+65",
  slovenia: "+386",
  "south-africa": "+27", // Added from original list as it was missing a prefix
  spain: "+34",
  "sri-lanka": "+94",
  sweden: "+46",
  switzerland: "+41",
  taiwan: "+886",
  thailand: "+66",
  turkey: "+90",
  ukraine: "+380",
  uae: "+971",
  "united-kingdom": "+44",
  "united-states": "+1",
  uruguay: "+598",
  venezuela: "+58",
  vietnam: "+84",
  // Add other new countries from the provided list
  "american-samoa": "+1-684",
  anguilla: "+1-264",
  aruba: "+297",
  barbados: "+1-246",
  belize: "+501",
  benin: "+229",
  bermuda: "+1-441",
  bhutan: "+975",
  bonaire: "+599", // Bonaire, Sint Eustatius i Saba
  "british-indian-ocean": "+246",
  brunei: "+673",
  "burkina-faso": "+226",
  burundi: "+257",
  "cape-verde": "+238",
  "cayman-islands": "+1-345",
  "central-african-republic": "+236",
  chad: "+235",
  "christmas-island": "+61",
  "cocos-islands": "+61",
  comoros: "+269",
  congo: "+242",
  "cook-islands": "+682",
  cuba: "+53",
  curacao: "+599",
  djibouti: "+253",
  dominica: "+1-767",
  "dominican-republic": "+1-809",
  "el-salvador": "+503",
  "equatorial-guinea": "+240",
  eritrea: "+291",
  "falkland-islands": "+500",
  "faroe-islands": "+298",
  fiji: "+679",
  finland: "+358",
  france: "+33",
  "french-guiana": "+594",
  "french-polynesia": "+689",
  "french-southern-territories": "+262",
  gabon: "+241",
  gambia: "+220",
  gibraltar: "+350",
  greenland: "+299",
  grenada: "+1-473",
  guadeloupe: "+590",
  guam: "+1-671",
  guernsey: "+44-1481",
  guinea: "+224",
  "guinea-bissau": "+245",
  guyana: "+592",
  haiti: "+509",
  "heard-mcdonald-islands": "+672",
  vatican: "+379", // Holy See (Vatican City State)
  "isle-of-man": "+44-1624",
  jamaica: "+1-876",
  kiribati: "+686",
  kosovo: "+383",
  kyrgyzstan: "+996",
  laos: "+856",
  lesotho: "+266",
  liberia: "+231",
  liechtenstein: "+423",
  macao: "+853",
  macedonia: "+389", // North Macedonia
  madagascar: "+261",
  malawi: "+265",
  maldives: "+960",
  mali: "+223",
  "marshall-islands": "+692",
  martinique: "+596",
  mauritania: "+222",
  mauritius: "+230",
  mayotte: "+262",
  micronesia: "+691",
  mozambique: "+258",
  namibia: "+264",
  nauru: "+674",
  nepal: "+977",
  "new-caledonia": "+687",
  nicaragua: "+505",
  niger: "+227",
  "norfolk-island": "+672",
  "north-korea": "+850",
  "northern-mariana": "+1-670",
  oman: "+968",
  palau: "+680",
  palestine: "+970",
  panama: "+507",
  "papua-new-guinea": "+675",
  paraguay: "+595",
  pitcairn: "+64",
  "puerto-rico": "+1-787",
  rwanda: "+250",
  "saint-kitts-nevis": "+1-869",
  "saint-lucia": "+1-758",
  "saint-vincent": "+1-784",
  salvador: "+503",
  samoa: "+685",
  "san-marino": "+378",
  senegal: "+221",
  seychelles: "+248",
  "sierra-leone": "+232",
  "solomon-islands": "+677",
  somalia: "+252",
  "south-sudan": "+211",
  sudan: "+249",
  suriname: "+597",
  swaziland: "+268", // Eswatini
  syria: "+963",
  tajikistan: "+992",
  tanzania: "+255",
  togo: "+228",
  tokelau: "+690",
  tonga: "+676",
  "trinidad-tobago": "+1-868",
  tunisia: "+216",
  turkmenistan: "+993",
  tuvalu: "+688",
  uganda: "+256",
  uzbekistan: "+998",
  vanuatu: "+678",
  "western-sahara": "+212",
  zambia: "+260",
  zimbabwe: "+263",
}

// Mapowanie prefiksów do krajów
export const PHONE_PREFIX_COUNTRIES: Record<string, string> = {
  "+48": "poland",
  "+49": "germany",
  "+420": "czechia",
  "+421": "slovakia",
  "+93": "afghanistan",
  "+355": "albania",
  "+213": "algeria",
  "+376": "andorra",
  "+244": "angola",
  "+54": "argentina",
  "+374": "armenia",
  "+61": "australia",
  "+43": "austria",
  "+994": "azerbaijan",
  "+1-242": "bahamas",
  "+973": "bahrain",
  "+880": "bangladesh",
  "+1-246": "barbados",
  "+501": "belize",
  "+229": "benin",
  "+1-441": "bermuda",
  "+975": "bhutan",
  "+297": "bonaire",
  "+246": "british-indian-ocean",
  "+673": "brunei",
  "+375": "belarus",
  "+32": "belgium",
  "+60": "malaysia",
  "+356": "malta",
  "+52": "mexico",
  "+373": "moldova",
  "+377": "monaco",
  "+976": "mongolia",
  "+382": "montenegro",
  "+212": "morocco",
  "+31": "netherlands",
  "+64": "new-zealand",
  "+234": "nigeria",
  "+47": "norway",
  "+92": "pakistan",
  "+51": "peru",
  "+63": "philippines",
  "+351": "portugal",
  "+974": "qatar",
  "+40": "romania",
  "+7": "russia",
  "+966": "saudi-arabia",
  "+381": "serbia",
  "+65": "singapore",
  "+386": "slovenia",
  "+27": "south-africa",
  "+34": "spain",
  "+94": "sri-lanka",
  "+46": "sweden",
  "+41": "switzerland",
  "+886": "taiwan",
  "+66": "thailand",
  "+90": "turkey",
  "+380": "ukraine",
  "+971": "uae",
  "+44": "united-kingdom",
  "+1": "united-states",
  "+598": "uruguay",
  "+58": "venezuela",
  "+84": "vietnam",
  "+1-684": "american-samoa",
  "+1-264": "anguilla",
  "+599": "curacao",
  "+1-876": "jamaica",
  "+686": "kiribati",
  "+383": "kosovo",
  "+996": "kyrgyzstan",
  "+856": "laos",
  "+266": "lesotho",
  "+231": "liberia",
  "+423": "liechtenstein",
  "+853": "macao",
  "+389": "macedonia",
  "+261": "madagascar",
  "+265": "malawi",
  "+960": "maldives",
  "+223": "mali",
  "+692": "marshall-islands",
  "+596": "martinique",
  "+222": "mauritania",
  "+230": "mauritius",
  "+262": "mayotte",
  "+691": "micronesia",
  "+258": "mozambique",
  "+264": "namibia",
  "+674": "nauru",
  "+977": "nepal",
  "+687": "new-caledonia",
  "+505": "nicaragua",
  "+227": "niger",
  "+672": "norfolk-island",
  "+850": "north-korea",
  "+1-670": "northern-mariana",
  "+968": "oman",
  "+680": "palau",
  "+970": "palestine",
  "+507": "panama",
  "+675": "papua-new-guinea",
  "+595": "paraguay",
  "+685": "samoa",
  "+378": "san-marino",
  "+221": "senegal",
  "+248": "seychelles",
  "+232": "sierra-leone",
  "+677": "solomon-islands",
  "+252": "somalia",
  "+211": "south-sudan",
  "+249": "sudan",
  "+597": "suriname",
  "+268": "swaziland",
  "+963": "syria",
  "+992": "tajikistan",
  "+255": "tanzania",
  "+228": "togo",
  "+690": "tokelau",
  "+676": "tonga",
  "+1-868": "trinidad-tobago",
  "+216": "tunisia",
  "+993": "turkmenistan",
  "+688": "tuvalu",
  "+256": "uganda",
  "+998": "uzbekistan",
  "+678": "vanuatu",
  "+379": "vatican",
}

// Mapowanie nazw krajów na polskie nazwy do wyświetlania
export const COUNTRY_NAMES_PL: Record<string, string> = {
  poland: "Polska",
  germany: "Niemcy",
  czechia: "Republika Czeska",
  slovakia: "Słowacja",
  afghanistan: "Afganistan",
  albania: "Albania",
  algeria: "Algieria",
  "american-samoa": "Samoa Amerykańskie",
  andorra: "Andora",
  angola: "Angola",
  anguilla: "Anguilla",
  "antigua-barbuda": "Antigua i Barbuda",
  "saudi-arabia": "Arabia Saudyjska",
  argentina: "Argentyna",
  armenia: "Armenia",
  aruba: "Aruba",
  australia: "Australia",
  austria: "Austria",
  azerbaijan: "Azerbejdżan",
  bahamas: "Bahamy",
  bahrain: "Bahrajn",
  bangladesh: "Bangladesz",
  barbados: "Barbados",
  belarus: "Białoruś",
  belgium: "Belgia",
  belize: "Belize",
  benin: "Benin",
  bermuda: "Bermudy",
  bhutan: "Bhutan",
  bolivia: "Boliwia",
  bonaire: "Bonaire, Sint Eustatius i Saba",
  "bosnia-herzegovina": "Bośnia i Hercegowina",
  botswana: "Botswana",
  brazil: "Brazylia",
  "british-indian-ocean": "Brytyjskie Terytorium Oceanu Indyjskiego",
  brunei: "Brunei",
  bulgaria: "Bułgaria",
  "burkina-faso": "Burkina Faso",
  burundi: "Burundi",
  "ivory-coast": "Wybrzeże Kości Słoniowej",
  cambodia: "Kambodża",
  cameroon: "Kamerun",
  canada: "Kanada",
  "cape-verde": "Wyspy Zielonego Przylądka",
  "cayman-islands": "Kajmany",
  "central-african-republic": "Republika Środkowoafrykańska",
  chad: "Czad",
  chile: "Chile",
  china: "Chiny",
  "christmas-island": "Wyspa Bożego Narodzenia",
  "cocos-islands": "Wyspy Kokosowe (Keelinga)",
  colombia: "Kolumbia",
  comoros: "Komory",
  congo: "Kongo",
  "cook-islands": "Wyspy Cooka",
  "costa-rica": "Kostaryka",
  croatia: "Chorwacja",
  cuba: "Kuba",
  curacao: "Curacao",
  cyprus: "Cypr",
  denmark: "Dania",
  djibouti: "Dżibuti",
  dominica: "Dominika",
  "dominican-republic": "Republika Dominikany",
  "east-timor": "Wschodni Timor",
  ecuador: "Ekwador",
  egypt: "Egipt",
  "el-salvador": "Salwador",
  "equatorial-guinea": "Gwinea Równikowa",
  eritrea: "Erytrea",
  estonia: "Estonia",
  ethiopia: "Etiopia",
  "falkland-islands": "Falklandy (Malwiny)",
  "faroe-islands": "Wyspy Owcze",
  fiji: "Fidżi",
  finland: "Finlandia",
  france: "Francja",
  "french-guiana": "Gujana Francuska",
  "french-polynesia": "Polinezja Francuska",
  "french-southern-territories": "Francuskie Terytoria Południowe",
  gabon: "Gabon",
  gambia: "Gambia",
  georgia: "Gruzja",
  ghana: "Ghana",
  gibraltar: "Gibraltar",
  greece: "Grecja",
  greenland: "Grenlandia",
  grenada: "Grenada",
  guadeloupe: "Gwadelupa",
  guam: "Guam",
  guatemala: "Gwatemala",
  guernsey: "Guernsey",
  guinea: "Republika Gwinea",
  "guinea-bissau": "Gwinea Bissau",
  guyana: "Gujana",
  haiti: "Haiti",
  "heard-mcdonald-islands": "Wyspy Heard i McDonalda",
  vatican: "Stolica Apostolska",
  honduras: "Honduras",
  "hong-kong": "Hongkong",
  hungary: "Węgry",
  iceland: "Islandia",
  india: "Indie",
  indonesia: "Indonezja",
  iran: "Iran",
  iraq: "Irak",
  ireland: "Irlandia",
  "isle-of-man": "Wyspa Man",
  israel: "Izrael",
  italy: "Włochy",
  jamaica: "Jamajka",
  japan: "Japonia",
  yemen: "Jemen",
  jordan: "Jordania",
  kazakhstan: "Kazachstan",
  kenya: "Kenia",
  kiribati: "Kiribati",
  kosovo: "Kosowo",
  kuwait: "Kuwejt",
  kyrgyzstan: "Kirgistan",
  laos: "Laos",
  latvia: "Łotwa",
  lebanon: "Liban",
  lesotho: "Lesotho",
  liberia: "Liberia",
  libya: "Libia",
  liechtenstein: "Liechtenstein",
  lithuania: "Litwa",
  luxembourg: "Luksemburg",
  macao: "Makao",
  macedonia: "Macedonia",
  madagascar: "Madagaskar",
  malawi: "Malawi",
  maldives: "Malediwy",
  mali: "Mali",
  marshall_islands: "Wyspy Marshalla",
  martinique: "Martynika",
  mauritania: "Mauretania",
  mauritius: "Mauritius",
  mayotte: "Majotta",
  micronesia: "Mikronezja",
  mozambique: "Mozambik",
  myanmar2: "Myanmar", // Duplicate, keep for now as in original list
  namibia: "Namibia",
  nauru: "Nauru",
  nepal: "Nepal",
  netherlands: "Holandia",
  "new-caledonia": "Nowa Kaledonia",
  "new-zealand": "Nowa Zelandia",
  nicaragua: "Nikaragua",
  niger: "Niger",
  nigeria: "Nigeria",
  "norfolk-island": "Wyspa Norfolk",
  "north-korea": "Korea Północna",
  "northern-mariana": "Mariany Północne",
  norway: "Norwegia",
  oman: "Oman",
  pakistan: "Pakistan",
  palau: "Palau",
  palestine: "Palestyna",
  panama: "Panama",
  "papua-new-guinea": "Papua Nowa Gwinea",
  paraguay: "Paragwaj",
  peru: "Peru",
  philippines: "Filipiny",
  pitcairn: "Pitcairn",
  portugal: "Portugalia",
  "puerto-rico": "Portoryko",
  qatar: "Katar",
  romania: "Rumunia",
  russia: "Rosja",
  rwanda: "Rwanda",
  "saint-kitts-nevis": "Saint Kitts i Nevis",
  "saint-lucia": "Saint Lucia",
  "saint-vincent": "Saint Vincent i Grenadyny",
  salvador: "Salwador",
  samoa: "Samoa",
  "san-marino": "San Marino",
  senegal: "Senegal",
  serbia: "Serbia",
  seychelles: "Seszele",
  "sierra-leone": "Sierra Leone",
  singapore: "Singapur",
  slovenia: "Słowenia",
  "solomon-islands": "Wyspy Salomona",
  somalia: "Somalia",
  "south-korea": "Korea Południowa",
  "south-sudan": "Południowy Sudan",
  spain: "Hiszpania",
  "sri-lanka": "Sri Lanka",
  sudan: "Sudan",
  suriname: "Surinam",
  swaziland: "Suazi",
  sweden: "Szwecja",
  switzerland: "Szwajcaria",
  syria: "Syria",
  taiwan: "Tajwan",
  tajikistan: "Tadżykistan",
  tanzania: "Tanzania",
  thailand: "Tajlandia",
  "east-timor2": "Timor Wschodni", // Duplicate, keep for now as in original list
  togo: "Togo",
  tokelau: "Tokelau",
  tonga: "Tonga",
  "trinidad-tobago": "Trynidad i Tobago",
  tunisia: "Tunezja",
  turkey: "Turcja",
  turkmenistan: "Turkmenistan",
  tuvalu: "Tuvalu",
  uganda: "Uganda",
  ukraine: "Ukraina",
  uae: "Zjednoczone Emiraty Arabskie",
  "united-states": "Stany Zjednoczone",
  "south-korea": "Korea Południowa",
  "south-sudan": "Południowy Sudan",
  spain: "Hiszpania",
  "sri-lanka": "Sri Lanka",
  sudan: "Sudan",
  suriname: "Surinam",
  swaziland: "Suazi",
  sweden: "Szwecja",
  switzerland: "Szwajcaria",
  syria: "Syria",
  taiwan: "Tajwan",
  tajikistan: "Tadżykistan",
  tanzania: "Tanzania",
  thailand: "Tajlandia",
  togo: "Togo",
  tokelau: "Tokelau",
  tonga: "Tonga",
  "trinidad-tobago": "Trynidad i Tobago",
  tunisia: "Tunezja",
  turkey: "Turcja",
  turkmenistan: "Turkmenistan",
  tuvalu: "Tuvalu",
  uganda: "Uganda",
  ukraine: "Ukraina",
  uae: "Zjednoczone Emiraty Arabskie",
  "united-kingdom": "Wielka Brytania",
  uruguay: "Urugwaj",
  uzbekistan: "Uzbekistan",
  vanuatu: "Vanuatu",
  vatican2: "Watykan", // Duplicate, keep for now as in original list
  venezuela: "Wenezuela",
  vietnam: "Wietnam",
  "western-sahara": "Sahara Zachodnia",
  yemen2: "Jemen", // Duplicate, keep for now as in original list
  zambia: "Zambia",
  zimbabwe: "Zimbabwe",
}

// English display names for all countries (always shown in English, sorted alphabetically where used)
export const COUNTRY_NAMES_EN: Record<string, string> = Object.keys(COUNTRY_NAMES_PL).reduce(
  (acc, key) => {
    const normalized = key
      .replace(/_/g, " ")
      .replace(/-/g, " ")
      .replace(/\s+/g, " ")
      .trim()
    const label = normalized.replace(/\b\w/g, (char) => char.toUpperCase())
    acc[key] = label
    return acc
  },
  {} as Record<string, string>
)

/** Maps invoice/OCR country text to internal slug used in selects (matches COUNTRY_NAMES_PL keys). */
export function normalizeCountryKeyFromAny(input: string | undefined | null): string {
  const raw = (input ?? "").trim()
  if (!raw) return ""
  if (raw in COUNTRY_NAMES_PL) return raw
  const lower = raw.toLowerCase()
  for (const [key, plLabel] of Object.entries(COUNTRY_NAMES_PL)) {
    if ((plLabel as string).toLowerCase() === lower) return key
  }
  const synonyms: Record<string, string> = {
    schweiz: "switzerland",
    switzerland: "switzerland",
    schwajcaria: "switzerland",
    polska: "poland",
    poland: "poland",
    deutschland: "germany",
    germany: "germany",
    österreich: "austria",
    osterreich: "austria",
  }
  if (synonyms[lower]) return synonyms[lower]
  return ""
}
